version: "4"
services:
  mongodb:
    image: mongo:7.0.5
    container_name: mongodb
    ports:
      - "2717:2717"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data:/data/db
    