version: "3.8"
services:
  inventory-service-postgres:
    image: postgres:15
    container_name: inventory-service-postgres
    restart: always
    environment:
      POSTGRES_DB: inventory_service
      POSTGRES_USER: adrien
      POSTGRES_PASSWORD: franto
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  inventory-service:
    build: .
    container_name: inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - inventory-service-postgres
    restart: always
